#encoding: utf-8

namespace :insert do

  desc "Insert Required data to the tables"
  task :data => :environment do
  	City.create([
	  { :city_name => "Port Blair", :time_zone => "UTC+05:30" },
	  { :city_name => "Guntur", :time_zone => "UTC+05:30" },
	  { :city_name => "Hyderabad", :time_zone => "UTC+05:30" },
	  { :city_name => "Vijayawada", :time_zone => "UTC+05:30" },
	  { :city_name => "Visakhapatnam", :time_zone => "UTC+05:30" },
	  { :city_name => "Warangal", :time_zone => "UTC+05:30" },
	  { :city_name => "Itanagar", :time_zone => "UTC+05:30" },
	  { :city_name => "Dibrugarh", :time_zone => "UTC+05:30" },
	  { :city_name => "Guwahati", :time_zone => "UTC+05:30" },
	  { :city_name => "Nagaon", :time_zone => "UTC+05:30" },
	  { :city_name => "Silchar", :time_zone => "UTC+05:30" },
	  { :city_name => "Bhagalpur", :time_zone => "UTC+05:30" },
	  { :city_name => "Biharsharif", :time_zone => "UTC+05:30" },
	  { :city_name => "Gaya", :time_zone => "UTC+05:30" },
	  { :city_name => "Muzaffarpur", :time_zone => "UTC+05:30" },
	  { :city_name => "Patna", :time_zone => "UTC+05:30" },
	  { :city_name => "Chandigarh", :time_zone => "UTC+05:30" },
	  { :city_name => "Bhilai Nagar", :time_zone => "UTC+05:30" },
	  { :city_name => "Bilaspur", :time_zone => "UTC+05:30" },
	  { :city_name => "Durg", :time_zone => "UTC+05:30" },
	  { :city_name => "Korba", :time_zone => "UTC+05:30" },
	  { :city_name => "Raipur", :time_zone => "UTC+05:30" },
	  { :city_name => "Silvassa", :time_zone => "UTC+05:30" },
	  { :city_name => "Daman", :time_zone => "UTC+05:30" },
	  { :city_name => "Delhi", :time_zone => "UTC+05:30" },
	  { :city_name => "Panaji", :time_zone => "UTC+05:30" },
	  { :city_name => "Ahmedabad", :time_zone => "UTC+05:30" },
	  { :city_name => "Bhavnagar", :time_zone => "UTC+05:30" },
	  { :city_name => "Rajkot", :time_zone => "UTC+05:30" },
	  { :city_name => "Surat", :time_zone => "UTC+05:30" },
	  { :city_name => "Vadodara", :time_zone => "UTC+05:30" },
	  { :city_name => "Faridabad", :time_zone => "UTC+05:30" },
	  { :city_name => "Gurgaon", :time_zone => "UTC+05:30" },
	  { :city_name => "Hisar", :time_zone => "UTC+05:30" },
	  { :city_name => "Panipat", :time_zone => "UTC+05:30" },
	  { :city_name => "Rohtak", :time_zone => "UTC+05:30" },
	  { :city_name => "Shimla", :time_zone => "UTC+05:30" },
	  { :city_name => "Anantnag", :time_zone => "UTC+05:30" },
	  { :city_name => "Jammu", :time_zone => "UTC+05:30" },
	  { :city_name => "Srinagar", :time_zone => "UTC+05:30" },
	  { :city_name => "Bokaro Steel", :time_zone => "UTC+05:30" },
	  { :city_name => "Dhanbad", :time_zone => "UTC+05:30" },
	  { :city_name => "Jamshedpur", :time_zone => "UTC+05:30" },
	  { :city_name => "Mango", :time_zone => "UTC+05:30" },
	  { :city_name => "Ranchi", :time_zone => "UTC+05:30" },
	  { :city_name => "Bangalore", :time_zone => "UTC+05:30" },
	  { :city_name => "Belgaum", :time_zone => "UTC+05:30" },
	  { :city_name => "Dharwad", :time_zone => "UTC+05:30" },
	  { :city_name => "Gulbarga", :time_zone => "UTC+05:30" },
	  { :city_name => "Hubliﾠ", :time_zone => "UTC+05:30" },
	  { :city_name => "Mysore", :time_zone => "UTC+05:30" },
	  { :city_name => "Kochi", :time_zone => "UTC+05:30" },
	  { :city_name => "Kollam", :time_zone => "UTC+05:30" },
	  { :city_name => "Kozhikode", :time_zone => "UTC+05:30" },
	  { :city_name => "Thrissur", :time_zone => "UTC+05:30" },
	  { :city_name => "Trivandrum", :time_zone => "UTC+05:30" },
	  { :city_name => "Kavaratti", :time_zone => "UTC+05:30" },
	  { :city_name => "Bhopal", :time_zone => "UTC+05:30" },
	  { :city_name => "Gwalior", :time_zone => "UTC+05:30" },
	  { :city_name => "Indore", :time_zone => "UTC+05:30" },
	  { :city_name => "Jabalpur", :time_zone => "UTC+05:30" },
	  { :city_name => "Ujjain", :time_zone => "UTC+05:30" },
	  { :city_name => "Chinchwad", :time_zone => "UTC+05:30" },
	  { :city_name => "Mumbai", :time_zone => "UTC+05:30" },
	  { :city_name => "Nagpur", :time_zone => "UTC+05:30" },
	  { :city_name => "Navi Mumbai", :time_zone => "UTC+05:30" },
	  { :city_name => "Pimpri", :time_zone => "UTC+05:30" },
	  { :city_name => "Pune", :time_zone => "UTC+05:30" },
	  { :city_name => "Thane", :time_zone => "UTC+05:30" },
	  { :city_name => "Imphal", :time_zone => "UTC+05:30" },
	  { :city_name => "Shillong", :time_zone => "UTC+05:30" },
	  { :city_name => "Aizawl", :time_zone => "UTC+05:30" },
	  { :city_name => "Dimapur", :time_zone => "UTC+05:30" },
	  { :city_name => "Bhubaneswar", :time_zone => "UTC+05:30" },
	  { :city_name => "Brahmapur", :time_zone => "UTC+05:30" },
	  { :city_name => "Cuttack", :time_zone => "UTC+05:30" },
	  { :city_name => "Puriﾠ", :time_zone => "UTC+05:30" },
	  { :city_name => "Raurkela", :time_zone => "UTC+05:30" },
	  { :city_name => "Town", :time_zone => "UTC+05:30" },
	  { :city_name => "Town", :time_zone => "UTC+05:30" },
	  { :city_name => "Ozhukarai", :time_zone => "UTC+05:30" },
	  { :city_name => "Puducherry", :time_zone => "UTC+05:30" },
	  { :city_name => "Amritsar", :time_zone => "UTC+05:30" },
	  { :city_name => "Bathinda", :time_zone => "UTC+05:30" },
	  { :city_name => "Jalandhar", :time_zone => "UTC+05:30" },
	  { :city_name => "Ludhiana", :time_zone => "UTC+05:30" },
	  { :city_name => "Patiala", :time_zone => "UTC+05:30" },
	  { :city_name => "Ajmer", :time_zone => "UTC+05:30" },
	  { :city_name => "Bikaner", :time_zone => "UTC+05:30" },
	  { :city_name => "Jaipur", :time_zone => "UTC+05:30" },
	  { :city_name => "Jodhpur", :time_zone => "UTC+05:30" },
	  { :city_name => "Kota", :time_zone => "UTC+05:30" },
	  { :city_name => "Gangtok", :time_zone => "UTC+05:30" },
	  { :city_name => "Chennai", :time_zone => "UTC+05:30" },
	  { :city_name => "Coimbatore", :time_zone => "UTC+05:30" },
	  { :city_name => "Madurai", :time_zone => "UTC+05:30" },
	  { :city_name => "Salem", :time_zone => "UTC+05:30" },
	  { :city_name => "Tiruchirappalli", :time_zone => "UTC+05:30" },
	  { :city_name => "Agartala", :time_zone => "UTC+05:30" },
	  { :city_name => "Agra", :time_zone => "UTC+05:30" },
	  { :city_name => "Ghaziabad", :time_zone => "UTC+05:30" },
	  { :city_name => "Kanpur", :time_zone => "UTC+05:30" },
	  { :city_name => "Lucknow", :time_zone => "UTC+05:30" },
	  { :city_name => "Meerut", :time_zone => "UTC+05:30" },
	  { :city_name => "Dehradun", :time_zone => "UTC+05:30" },
	  { :city_name => "Haldwani", :time_zone => "UTC+05:30" },
	  { :city_name => "Hardwar", :time_zone => "UTC+05:30" },
	  { :city_name => "Kathgodam", :time_zone => "UTC+05:30" },
	  { :city_name => "Rudrapur", :time_zone => "UTC+05:30" },
	  { :city_name => "Asansol", :time_zone => "UTC+05:30" },
	  { :city_name => "Durgapur", :time_zone => "UTC+05:30" },
	  { :city_name => "Howrah", :time_zone => "UTC+05:30" },
	  { :city_name => "Kolkata", :time_zone => "UTC+05:30" },
	  { :city_name => "Siliguri", :time_zone => "UTC+05:30" }
	])
		puts "=================City records inserted.================"
  end
end
